apiVersion: v1
kind: ConfigMap
metadata:
  name: adsoftsito-config
  labels:
    app: postgres
data:
  DEV_SECRET_KEY: i-love-adsoftsito-dev
  DEV_DATABASE: llmdwjpy
  DEV_USER: llmdwjpy
  DEV_PASSWORD: zMqdX93WZUqtWNvgKw2H221OGuItj0wy
  DEV_HOST: rain.db.elephantsql.com 
  DEV_PORT: "5432"
