apiVersion: apps/v1
kind: Deployment
metadata:
  name: lilliamwitham
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lilliamwitham
  template:
    metadata:
      labels:
        app: lilliamwitham
    spec:
      containers:
      - image: okteto.dev/lilliamwitham:latest
        name: lilliamwitham
        #envFrom:
        #- configMapRef:
        #    name: erick-config
        livenessProbe:
          httpGet:
            path: /ht/
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: lilliamwitham
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "lilliamwitham"
    port: 8080
  selector:
    app: lilliamwitham
